# -*- coding: utf-8 -*-
"""jpg_to_png.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12pIkGa8FVMznxv7swQ-KY3BNsBhDkOVI
"""

from rembg import remove
from PIL import Image
input_path = 'image.jpg'
output_path = 'output.png'
input = Image.open(input_path)
output = remove(input)
output.save(output_path)